#ifndef EFI_PROTOCOLS_DEVICE_PATH
#define EFI_PROTOCOLS_DEVICE_PATH

////
// EFI Device Path Protocol
///

#define EFI_DEVICE_PATH_PROTOCOL_GUID {0x09576e91,0x6d3f,0x11d2,{0x8e,0x39,0x00,0xa0,0xc9,0x69,0x72,0x3b}}

typedef struct _EFI_DEVICE_PATH_PROTOCOL EFI_DEVICE_PATH_PROTOCOL;

typedef struct _EFI_DEVICE_PATH_PROTOCOL {
	UINT8 Type;
	UINT8 SubType;
	UINT8 Length[2];
} EFI_DEVICE_PATH_PROTOCOL;

////
// EFI Device Path Utilities Protocol
///

#define EFI_DEVICE_PATH_UTILITIES_PROTOCOL_GUID {0x379be4e,0xd706,0x437d, {0xb0,0x37,0xed,0xb8,0x2f,0xb7,0x72,0xa4}}

typedef struct _EFI_DEVICE_PATH_UTILITIES_PROTOCOL EFI_DEVICE_PATH_UTILITIES_PROTOCOL;

typedef
UINTN
( *EFI_DEVICE_PATH_UTILS_GET_DEVICE_PATH_SIZE)(
	  EFI_DEVICE_PATH_PROTOCOL *DevicePath
);

typedef
EFI_DEVICE_PATH_PROTOCOL*
( *EFI_DEVICE_PATH_UTILS_DUP_DEVICE_PATH)(
	  EFI_DEVICE_PATH_PROTOCOL *DevicePath
);

typedef
EFI_DEVICE_PATH_PROTOCOL*
( *EFI_DEVICE_PATH_UTILS_APPEND_PATH)(
	  EFI_DEVICE_PATH_PROTOCOL *Src1,
	  EFI_DEVICE_PATH_PROTOCOL *Src2
);

typedef
EFI_DEVICE_PATH_PROTOCOL*
( *EFI_DEVICE_PATH_UTILS_APPEND_NODE)(
	  EFI_DEVICE_PATH_PROTOCOL *DevicePath,
	  EFI_DEVICE_PATH_PROTOCOL *DeviceNode
);

typedef
EFI_DEVICE_PATH_PROTOCOL*
( *EFI_DEVICE_PATH_UTILS_APPEND_STANCE)(
	  EFI_DEVICE_PATH_PROTOCOL *DevicePath,
	  EFI_DEVICE_PATH_PROTOCOL *DevicePathInstance
);

typedef
EFI_DEVICE_PATH_PROTOCOL*
( *EFI_DEVICE_PATH_UTILS_GET_NEXT_STANCE)(
	  EFI_DEVICE_PATH_PROTOCOL **DevicePathInstance,
	 UINTN *DevicePathInstanceSize 
);

typedef
BOOLEAN
( *EFI_DEVICE_PATH_UTILS_IS_MULTI_STANCE)(
	  EFI_DEVICE_PATH_PROTOCOL *DevicePath
);

typedef
EFI_DEVICE_PATH_PROTOCOL*
( *EFI_DEVICE_PATH_UTILS_CREATE_NODE)(
	 UINT8 NodeType,
	 UINT8 NodeSubType,
	 UINT16 NodeLength
);

typedef struct _EFI_DEVICE_PATH_UTILITIES_PROTOCOL {
	EFI_DEVICE_PATH_UTILS_GET_DEVICE_PATH_SIZE GetDevicePathSize;
	EFI_DEVICE_PATH_UTILS_DUP_DEVICE_PATH DuplicateDevicePath;
	EFI_DEVICE_PATH_UTILS_APPEND_PATH AppendDevicePath;
	EFI_DEVICE_PATH_UTILS_APPEND_NODE AppendDeviceNode;
	EFI_DEVICE_PATH_UTILS_APPEND_STANCE AppendDevicePathInstance;
	EFI_DEVICE_PATH_UTILS_GET_NEXT_STANCE GetNextDevicePathInstance;
	EFI_DEVICE_PATH_UTILS_IS_MULTI_STANCE IsDevicePathMultiInstance;
	EFI_DEVICE_PATH_UTILS_CREATE_NODE CreateDeviceNode;
} EFI_DEVICE_PATH_UTILITIES_PROTOCOL;

#endif
